export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"


export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"

export const ADD_ADDRESS = "ADD_ADDRESS";
export const SELECT_ORDER_ADDRESS = "SELECT_ORDER_ADDRESS"

export const SET_CATEGORIES = "SET_CATEGORIES"

export const SET_PRODUCTS = "SET_PRODUCTS"

export const CHANGE_AREA_PINCODE = "CHANGE_AREA_PINCODE"

export const LOAD_LATEST_CART = "LOAD_LATEST_CART"

export const SIGNIN_USER = "SIGNIN_USER"

export const LOGOUT_USER = "LOGOUT_USER"

// PRE ORDER ACTIONS
export const ADD_COUPON_CODE = "ADD_COUPON_CODE"

export const ADD_DEALER_CODE = "ADD_DEALER_CODE"

export const ADD_ITEMS = "ADD_ITEMS"

export const ADD_ADDRESS_PRE = "ADD_ADDRESS_PRE"

