export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"


export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"

export const ADD_ADDRESS = "ADD_ADDRESS";
export const SELECT_ORDER_ADDRESS = "SELECT_ORDER_ADDRESS"

export const SET_CATEGORIES = "SET_CATEGORIES"

export const SET_PRODUCTS = "SET_PRODUCTS"

export const CHANGE_AREA_PINCODE = "CHANGE_AREA_PINCODE"

export const RECTIFY_CART_PRICE = "RECTIFY_CART_PRICE"
